In [1]:
import numpy as np

In [8]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [5]:
a = np.array([[10,20,30,40],[50,60,70,80]])

In [9]:
print(a)
print(a*2)

[[10 20 30 40]
 [50 60 70 80]]
[[ 20  40  60  80]
 [100 120 140 160]]


In [10]:
len(a)

2

In [12]:
len(a[1]);len(a[0])

4

In [14]:
a = np.array([[10,20,30,40],[50,60,70,80]])

In [15]:
d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])

In [16]:
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


# reshape

In [55]:
na = np.arange(12)
print(na)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
nb = na.reshape(3,4)
print(nb)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [38]:
nb = na.reshape(3,-1)          #  -1 = 알아서 처리해라
print(nb)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
nb = na.reshape(2,-1,2)
print(nb)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [56]:
nb = na.reshape(-1,2,2)
print(nb)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


# flatten , ravel

In [42]:
nc = nb.flatten()
print(nc)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:
nc = nb.ravel()
print(nc)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# dtype

In [65]:
a = np.array([1,2,3],dtype='int8')
print(a)

[1 2 3]


In [68]:
a = np.array([1,2,3,4,5])
idx = np.array([True,False,True,False,True,False,True,False,True,False])
print(idx[a])

[False  True False  True False]
